{
  "formatVersion": "1.1",
  "component": {
    "group": "dk.cachet",
    "module": "rad",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "g6c7r5tszjesre2nu7bska7cvq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-apache",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-auth",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "rad-1.0.3.jar",
          "url": "rad-1.0.3.jar",
          "size": 14686,
          "sha512": "25fa21f330e817f1c5e8a947f7338f00e40ee12ee10411bad60e84cecd2b9589bd6a7e1cbac67373473c042ca6cb578ceb0360c1da58cb0aafa5d6b56d65157b",
          "sha256": "b9581e46d899211de66d192601932f50c20702de850481739fab6a0f6d564010",
          "sha1": "55977f013a8a68caf4a3f7e4b7f1e2078ab0cc0a",
          "md5": "6caa2b028f0913517bb37dac5f011695"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0-rc6"
          }
        },
        {
          "group": "net.ltgt.gradle.incap",
          "module": "incap",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-metadata",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-metadata-specs",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-classinspector-elements",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-apache",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-auth",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "rad-1.0.3.jar",
          "url": "rad-1.0.3.jar",
          "size": 14686,
          "sha512": "25fa21f330e817f1c5e8a947f7338f00e40ee12ee10411bad60e84cecd2b9589bd6a7e1cbac67373473c042ca6cb578ceb0360c1da58cb0aafa5d6b56d65157b",
          "sha256": "b9581e46d899211de66d192601932f50c20702de850481739fab6a0f6d564010",
          "sha1": "55977f013a8a68caf4a3f7e4b7f1e2078ab0cc0a",
          "md5": "6caa2b028f0913517bb37dac5f011695"
        }
      ]
    }
  ]
}
