{
  "formatVersion": "1.1",
  "component": {
    "group": "dk.cachet",
    "module": "kodegen",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "keibqdyvd5apfkyr6fypkwo2wq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-apache",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-auth",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodegen-1.0.0.jar",
          "url": "kodegen-1.0.0.jar",
          "size": 14781,
          "sha512": "fda7f36aebd8e60765ea26f2f8567bcfc3a58c627212cdabd0f516a962853eb5a4f4ebb453ab94138776beed055d0c984f7c4ac540f1265f381d13654515d7f3",
          "sha256": "a0fb16555f21122805cdc355568f5c36be6d4224d8e6a32c4ecf89d69f8e1dea",
          "sha1": "3714eceef2de2dcc8fbc37193d4f193ec4072483",
          "md5": "2d263940e24cea18f84871e013d1a59d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0-rc6"
          }
        },
        {
          "group": "net.ltgt.gradle.incap",
          "module": "incap",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-metadata",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-metadata-specs",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-classinspector-elements",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-apache",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-auth",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodegen-1.0.0.jar",
          "url": "kodegen-1.0.0.jar",
          "size": 14781,
          "sha512": "fda7f36aebd8e60765ea26f2f8567bcfc3a58c627212cdabd0f516a962853eb5a4f4ebb453ab94138776beed055d0c984f7c4ac540f1265f381d13654515d7f3",
          "sha256": "a0fb16555f21122805cdc355568f5c36be6d4224d8e6a32c4ecf89d69f8e1dea",
          "sha1": "3714eceef2de2dcc8fbc37193d4f193ec4072483",
          "md5": "2d263940e24cea18f84871e013d1a59d"
        }
      ]
    }
  ]
}
