{
  "formatVersion": "1.1",
  "component": {
    "group": "dk.cachet",
    "module": "rad",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "6by4sauc7jdptgn4muslrff2we"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-apache",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-auth",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "rad-1.0.1.jar",
          "url": "rad-1.0.1.jar",
          "size": 12350,
          "sha512": "d1ca7c845b3343ec574415e24ee9e8073119b3711ae49a994fcb0dd955ad731dd8777816f5b237bac8c784b1175d8f26333b0dc4aa66e2c4e329f7de20e09543",
          "sha256": "a9edbf962d66059d372803afc9df86019d47cd9ab9375d945806f8e07d54cab9",
          "sha1": "b6d369a138024f708a6864d1a2b5061c83c61bb5",
          "md5": "74ddab15631ff2673156ff5d95322c6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0-rc6"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-metadata",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-metadata-specs",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-classinspector-elements",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-apache",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-auth",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "rad-1.0.1.jar",
          "url": "rad-1.0.1.jar",
          "size": 12350,
          "sha512": "d1ca7c845b3343ec574415e24ee9e8073119b3711ae49a994fcb0dd955ad731dd8777816f5b237bac8c784b1175d8f26333b0dc4aa66e2c4e329f7de20e09543",
          "sha256": "a9edbf962d66059d372803afc9df86019d47cd9ab9375d945806f8e07d54cab9",
          "sha1": "b6d369a138024f708a6864d1a2b5061c83c61bb5",
          "md5": "74ddab15631ff2673156ff5d95322c6f"
        }
      ]
    }
  ]
}
