{
  "formatVersion": "1.1",
  "component": {
    "group": "dk.cachet.rad",
    "module": "rad",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "jj5jhg6zyff4detdfkd26c24im"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-apache",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-auth",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "rad-1.0.0.jar",
          "url": "rad-1.0.0.jar",
          "size": 19953,
          "sha512": "2b99274b564b53a2766ccd6c88975ee991bc5e07306ced9cda0de0f1054a34fcb48506d782db4110c19d0117be74a75c85e2cdbd7d50ca5c569f78d01070001e",
          "sha256": "ae77a620b387cd6b422259a231fdd02de73bf538341238bf270a6df275ed15bc",
          "sha1": "afdda8dd593f105f5bb976520fcd43e056a7f5b6",
          "md5": "88386912254785893d98264305a645ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0-rc6"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-metadata",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-metadata-specs",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-classinspector-elements",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-apache",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-auth",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "rad-1.0.0.jar",
          "url": "rad-1.0.0.jar",
          "size": 19953,
          "sha512": "2b99274b564b53a2766ccd6c88975ee991bc5e07306ced9cda0de0f1054a34fcb48506d782db4110c19d0117be74a75c85e2cdbd7d50ca5c569f78d01070001e",
          "sha256": "ae77a620b387cd6b422259a231fdd02de73bf538341238bf270a6df275ed15bc",
          "sha1": "afdda8dd593f105f5bb976520fcd43e056a7f5b6",
          "md5": "88386912254785893d98264305a645ce"
        }
      ]
    }
  ]
}
